# Generated by Django 5.0.3 on 2024-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=200)),
                ('last', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('vaccinated', models.BooleanField()),
                ('photo_preference', models.BooleanField()),
                ('emergency_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
