# Generated by Django 5.0.3 on 2024-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_client_delete_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
            ],
        ),
    ]
