# Generated by Django 5.0.3 on 2024-03-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='days',
        ),
        migrations.AddField(
            model_name='class',
            name='friday',
            field=models.BooleanField(db_default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='monday',
            field=models.BooleanField(db_default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='saturday',
            field=models.BooleanField(db_default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='sunday',
            field=models.BooleanField(db_default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='thursday',
            field=models.BooleanField(db_default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='tuesday',
            field=models.BooleanField(db_default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='wednesday',
            field=models.BooleanField(db_default=False, max_length=200),
        ),
    ]
