# Generated by Django 5.0.3 on 2024-03-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_remove_class_days_class_friday_class_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='friday',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='monday',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='saturday',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='sunday',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='thursday',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='tuesday',
            field=models.BooleanField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='wednesday',
            field=models.BooleanField(max_length=200),
        ),
    ]
