# Generated by Django 5.0.3 on 2024-04-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_delete_signin_alter_class_friday_alter_class_monday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
    ]
