# Generated by Django 5.0.3 on 2024-04-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_rename_class_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField()),
                ('course_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
