# Generated by Django 5.0.3 on 2024-04-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_signin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.client'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.course'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
