# Generated by Django 5.0.3 on 2024-04-14 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0011_rename_client_id_signin_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='signin',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
