# Generated by Django 5.1a1 on 2025-01-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0012_alter_course_instructor_alter_signin_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resident_cost',
            field=models.IntegerField(default=0),
        ),
    ]
