# Generated by Django 5.1 on 2024-08-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0013_course_non_resident_cost_course_resident_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='non_resident_cost',
        ),
        migrations.RemoveField(
            model_name='course',
            name='resident_cost',
        ),
    ]
