# Generated by Django 5.0.4 on 2024-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0014_remove_course_non_resident_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nonres_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='res_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
