# Generated by Django 5.0.4 on 2025-07-31 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0013_course_resident_cost'),
        ('Database', '0015_course_nonres_cost_course_res_cost'),
    ]

    operations = [
    ]
