# Generated by Django 5.0.4 on 2025-07-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0016_merge_20250731_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='street1',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='street2',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='zip',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='non_resident_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='resident_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
