# Generated by Django 5.0.4 on 2025-07-31 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0017_remove_client_address_remove_course_nonres_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='course',
            name='nonres_cost',
        ),
        migrations.RemoveField(
            model_name='course',
            name='res_cost',
        ),
    ]
