# Generated by Django 5.0.4 on 2025-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0018_remove_client_address_remove_course_nonres_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_phone1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_phone2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='emt_info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
