# Generated by Django 5.0.4 on 2025-08-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0019_sheetimport_remove_client_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='non_resident_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='resident_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
