# Generated by Django 5.0.4 on 2025-08-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0020_alter_course_non_resident_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_resident',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
