# Generated by Django 5.0.4 on 2025-08-16 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0021_client_is_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='set_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2001, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_resident',
            field=models.BooleanField(default=False),
        ),
    ]
