# Generated by Django 5.2.5 on 2025-08-16 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0022_course_set_date_alter_client_is_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='set_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2001, 1, 1, 0, 0), null=True),
        ),
    ]
